### ISSUE TITLE
GNOME 3.16 support

### ISSUE THREAD

**Issue by r0bertw** [orangeshirt/gnome-shell-extension-touchpad-indicator#50]
This extension as at current github master doesn't work under GNOME 3.16.  I tried naively adding "3.16" to metadata.json and get an error "Schema org.gnome.settings-daemon.peripherals.touchpad could not be found".

**Comment by gearhead** [comment]
And in 3.14 (or whatever is in Ubuntu Gnome 14.04 LTS) it does not work
correctly. If it is installed and the touchpad is working then the mouse is
plugged in, it will switch off the touchpad. If the mouse is then
unplugged, it will not ever turn back on the touchpad. This has been tested
with all 3 modes. It worked beautifully in an earlier release of Gnome
(whatever was with Ubuntu 13.10)

**Comment by orangeshirt** [comment]
Sorry, but I stop the development of this extension, because I've no longer been using gnome shell.
The last version i used was 3.4.
Perhaps someone other could help you or you could fix the issue by yourself.

**Comment by RaphaelRochet** [comment]
Hi there,

I've done some work on it, seems now to work fine in 3.16 for me.

Please test :
https://github.com/RaphaelRochet/gnome-shell-extension-touchpad-indicator

**Comment by r0bertw** [comment]
Works for me too, cheers.

**Comment by fdinardo** [comment]
Works for me too, thanks!
Since orangeshirt will not maintain this extension anymore, do you think to merge your code with this?

**Comment by RaphaelRochet** [comment]
Sure.
